<?php

declare(strict_types=1);
/**
 * Unit testing StringClass 
 * 
 * ( including new functions 
 *   <code>str_contains()</code>, 
 *   <code>str_starts_with()</code> and 
 *   <code>str_ends_with()</code>
 * )
 * 
 * @author Sven Schrodt<sven@schrodt.club>
 * @link https://github.com/SchrodtSven/P8
 * @package P8
 * @version 0.1
 * @since 2023-04-25
 */

use PHPUnit\Framework\TestCase;
use SchrodtSven\P8\Internal\StringClass;
use SchrodtSven\P8\Internal\ListClass;


class StringClassTest extends TestCase
{

    

    /**
     * @dataProvider productListSupplier
     */
    public function testStringStartsEndsAndContains( 
                                                    string $txt,
                                                    string $start,
                                                    string $end,
                                                    string $mid
    )
    {
        $mock = new StringClass($txt);
        $this->assertTrue($mock->begins($start));
        $this->assertTrue($mock->ends($end));
        $this->assertTrue($mock->contains($mid));
    }


    /**
     * 
     * @dataProvider typeSupplier
     */
    public function testUnionTypeDeclaration(mixed $expression, string $status): void
    {
        if($status === 'ok') {
            $foo = StringClass::forceToBeStringClass($expression);
            $this->assertInstanceOf(StringClass::class, $foo);
            $this->assertTrue(is_string((string) $foo));
        } else {
            $this->expectError('TypeError');
            $foo = StringClass::forceToBeStringClass($expression);
        }
        
        
    }

    public function typeSupplier(): array
    {
        return [
            [true, 'ok'], 
            [false, 'ok'], 
            [null, 'ok'],
            ['example String', 'ok'],
            [new StringClass('Bar'), 'ok'],
            [ 1234, 'ok'], 
            [3.145, 'ok'],
            [[1,2,23,6], 'ok'],
            [new \stdClass(), 'notOk'],
            [new \DateTime(), 'notOk'],
            [new PhpToken(\T_ECHO, 'echo'), 'ok'],
        ];
    }


    public function productListSupplier(): array
    {
        return [
                ['Veal - Brisket, Provimi,bnls', 'Veal - Brisket', ',bnls', ' Brisket, '], 
                ['Oil - Coconut', 'Oil', 'conut', ' Cocon'], 
                ['Cookie Dough - Peanut Butter', 'Cookie Dough -', 'Peanut Butter', ' - Pe'], 
                ['Milk - Homo', 'Mi', 'Homo', 'k'], 
                ['Soup - Campbells Tomato Ravioli', 'Soup -', 'Tomato Ravioli', 'Campbells Tom'], 
                ['Molasses - Fancy', 'Mo', ' - Fancy', 's'], 
                ['Stock - Fish', 'Stock ', ' Fish', ' -'], 
                ['Beer - True North Lager', 'Beer', 'h Lager', ' North '], 
                ['Apron', 'Ap', 'on', 'pr'], 
                ['Peach - Fresh', 'Pea', 'resh', 'ch'], 
                ['Ginger - Pickled', 'Gin', ' Pickled', 'i'], 
                ['French Pastry - Mini Chocolate', 'French P', 'ni Chocolate', ' - Mini Choco'], 
                ['Cake - Night And Day Choclate', 'Cake - Ni', ' Choclate', '-'], 
                ['Salmon Steak - Cohoe 6 Oz', 'Salm', 'Cohoe 6 Oz', 'k - Cohoe 6'], 
                ['Pie Shell - 9', 'Pie She', 'l - 9', 'e S'], 
                ['Stock - Fish', 'Sto', '- Fish', 't'], 
                ['Oil - Olive Bertolli', 'Oil - Oli', 'ertolli', 'Olive Ber'], 
                ['Table Cloth 91x91 Colour', 'Tabl', ' Colour', 'Cloth 91'], 
                ['Buttons', 'But', 'ons', 'B'], 
                ['Duck - Legs', 'Duck ', ' Legs', 'c'], 
                ['Bread - Wheat Baguette', 'Brea', 'at Baguette', 'at Baguette'], 
                ['Bagelers - Cinn / Brown Sugar', 'Bagelers - Cinn', '/ Brown Sugar', 'n / Brown S'], 
                ['Island Oasis - Peach Daiquiri', 'Isla', ' Daiquiri', ' - P'], 
                ['Onions - Cooking', 'Onions', 'king', 'ions - C'], 
                ['Chocolate - Chips Compound', 'Choco', 'ompound', 'late '], 
                ['Bar Bran Honey Nut', 'Bar Br', 'oney Nut', 'r Bran'], 
                ['Currants', 'Cu', 'ants', 'ur'], 
                ['Nougat - Paste / Cream', 'Noug', 'ste / Cream', 'a'], 
                ['Aspic - Light', 'A', 'Light', 'Aspi'], 
                ['Ice Cream - Life Savers', 'Ice Cream - ', 'vers', 'am - L'], 
                ['Sprouts - Bean', 'Spr', 'Bean', 's'], 
                ['Venison - Racks Frenched', 'Venison -', ' Frenched', 'Racks French'], 
                ['Lotus Leaves', 'Lot', 'aves', 'L'], 
                ['Sauce - Hp', 'Sauce', ' - Hp', 'ce - '], 
                ['Wine - Gato Negro Cabernet', 'Wine - Gato N', ' Cabernet', 'ine - Gato Ne'], 
                ['Sugar - Invert', 'Sugar ', 'vert', 'ugar '], 
                ['Wine - Fat Bastard Merlot', 'Wine - Fat Ba', 'erlot', 'at Basta'], 
                ['Water - Evian 355 Ml', 'Water - E', '355 Ml', 'ter'], 
                ['Wine - Tio Pepe Sherry Fino', 'Wine -', 'Sherry Fino', ' Pepe Sherr'], 
                ['Fenngreek Seed', 'Fenng', 'k Seed', 'ee'], 
                ['Juice - Apple, 1.36l', 'Juice - Ap', 'le, 1.36l', ' Apple, 1'], 
                ['Egg Patty Fried', 'Egg P', ' Fried', ' Patt'], 
                ['Frangelico', 'Frang', 'lico', 'r'], 
                ['Wine - Red, Harrow Estates, Cab', 'Wi', 'ow Estates, Cab', 'Harr'], 
                ['Wine - Prem Select Charddonany', 'Wine - Prem Sel', 'Charddonany', 'lect Charddona'], 
                ['Bag - Regular Kraft 20 Lb', 'Bag - Regular', 'Kraft 20 Lb', 'lar Kraft 20 '], 
                ['Doilies - 10, Paper', 'Doil', 'aper', 'oilies '], 
                ['Mace', 'Ma', 'ce', 'c'], 
                ['Sauce - Mint', 'Sau', 'Mint', ' - '], 
                ['Pastry - Choclate Baked', 'Pastr', 'clate Baked', 'hocl'], 
                ['Shiratamako - Rice Flour', 'Shi', ' Flour', 'ako - Rice '], 
                ['Mustard - Pommery', 'Mustard', 'Pommery', 'd - '], 
                ['Hold Up Tool Storage Rack', 'Ho', 'Storage Rack', 'ld Up Tool St'], 
                ['Wine - White, Schroder And Schyl', 'Wine - ', 'nd Schyl', 'chroder'], 
                ['Silicone Parch. 16.3x24.3', 'Sil', '6.3x24.3', 'ch. 16.3x24.'], 
                ['Syrup - Monin - Granny Smith', 'Syrup - M', 'ny Smith', 'Syrup'], 
                ['Puree - Raspberry', 'Puree ', 'pberry', 'ree - Ras'], 
                ['Cheese - Wine', 'Chees', '- Wine', 'Cheese '], 
                ['Noodles - Cellophane, Thin', 'Noodles - C', 'ne, Thin', 'les - Celloph'], 
                ['Soup - Campbells Beef Strogonoff', 'Soup - Campbells', 'Strogonoff', 'up - Campbells '], 
                ['Sachet', 'Sac', 'chet', 'ach'], 
                ['Flour - Strong Pizza', 'Flou', 'ong Pizza', 'ur - St'], 
                ['Chocolate - Unsweetened', 'Cho', 'eetened', '- Unsw'], 
                ['Beer - Guiness', 'Beer', 'Guiness', ' Guine'], 
                ['Liqueur Banana, Ramazzotti', 'Liqu', 'mazzotti', 'ana, Ram'], 
                ['Sage - Fresh', 'Sage -', 'resh', 'ag'], 
                ['Rice Wine - Aji Mirin', 'Rice Wine', 'i Mirin', 'ce W'], 
                ['Easy Off Oven Cleaner', 'Easy Off', 'leaner', 'y Off Ov'], 
                ['Rosemary - Fresh', 'Rosem', ' Fresh', 'ry - F'], 
                ['Towels - Paper / Kraft', 'Towels - Pa', ' / Kraft', '- '], 
                ['Wine - White, Cooking', 'Wine ', ' Cooking', 'Wine '], 
                ['Sour Puss Sour Apple', 'So', 'Sour Apple', 'ss S'], 
                ['Glycerine', 'Glyce', 'rine', 'c'], 
                ['Veal - Nuckle', 'Ve', 'uckle', 'Nuck'], 
                ['Soap - Pine Sol Floor Cleaner', 'Soap - Pine S', 'Cleaner', 'ne '], 
                ['Ham - Cooked Bayonne Tinned', 'Ham -', 'yonne Tinned', 'oked Bayonn'], 
                ['Yokaline', 'Yo', 'line', 'ka'], 
                ['Chips Potato Reg 43g', 'Chips ', 'g 43g', 'tato R'], 
                ['Burger Veggie', 'Burger ', 'Veggie', 'ger'], 
                ['Pepper - Red Chili', 'Pe', 'hili', 'pe'], 
                ['Cleaner - Pine Sol', 'Cleaner -', 'Pine Sol', ' '], 
                ['Rice - Brown', 'Rice ', ' Brown', 'Ri'], 
                ['Cheese - Stilton', 'Chee', 'tilton', 'eese - S'], 
                ['Pears - Anjou', 'Pear', 'njou', 'Pears'], 
                ['Honey - Comb', 'Hone', ' Comb', '- Co'], 
                ['Bread - Roll, Whole Wheat', 'Br', 'hole Wheat', ','], 
                ['Lotus Leaves', 'Lotus', 'eaves', 's'], 
                ['Sprouts - Onion', 'Sprouts ', ' Onion', 'ts'], 
                ['Basil - Dry, Rubbed', 'Basil -', 'y, Rubbed', 'B'], 
                ['Wine - Segura Viudas Aria Brut', 'Win', 'iudas Aria Brut', ' - Segura Viu'], 
                ['Lady Fingers', 'La', 'gers', 'Lady '], 
                ['Steel Wool', 'St', ' Wool', 'te'], 
                ['Wine - Riesling Alsace Ac 2001', 'Wine - Ries', 'ce Ac 2001', ' Al'], 
                ['Icecream - Dstk Strw Chseck', 'Icecream - ', 'trw Chseck', 'tk Strw'], 
                ['Puree - Pear', 'P', ' Pear', 'e - P'], 
                ['Soup - Campbellschix Stew', 'Soup - Camp', 'schix Stew', ' - Campbellsc'], 
                ['Lobak', 'Lob', 'ak', 'Lob'], 
                ['Wine - Cotes Du Rhone Parallele', 'Win', 'one Parallele', 'Wine - Cotes'], 
                ['Bread - Italian Corn Meal Poly', 'Bread ', ' Meal Poly', 'ead - It'], 
                ['Cilantro / Coriander - Fresh', 'Cilantro / ', ' - Fresh', 'o / '], 
                ['Lamb - Whole, Frozen', 'Lamb -', 'Frozen', 'Whole, Fro'], 
                ['Dc Hikiage Hira Huba', 'Dc Hiki', 'Huba', 'kiage Hi'], 
                ['Daikon Radish', 'D', 'Radish', 'on Radi'], 
                ['Bandage - Finger Cots', 'B', 'r Cots', '- '], 
                ['Bread - Frozen Basket Variety', 'Bread - Frozen ', 'riety', 'read - Froze'], 
                ['Longos - Chicken Wings', 'Lon', 'icken Wings', 'Longos - C'], 
                ['Trueblue - Blueberry', 'Tr', 'lueberry', 'ueblu'], 
                ['Wine - Rioja Campo Viejo', 'Wine - Rio', 'po Viejo', 'e - Rioja '], 
                ['Peach - Fresh', 'Pe', 'resh', ' Fresh'], 
                ['Bread - Pita, Mini', 'Bread -', ', Mini', ' Pi'], 
                ['Chips Potato All Dressed - 43g', 'Chips', ' 43g', 'l'], 
                ['Coffee - Frthy Coffee Crisp', 'Coffee', 'fee Crisp', 'Coffee - Frt'], 
                ['Croissants Thaw And Serve', 'Croissant', 'Serve', 'issants Tha'], 
                ['Jolt Cola - Red Eye', 'Jolt ', 'ed Eye', 'Jol'], 
                ['Juice - Apple 284ml', 'J', 'e 284ml', ' App'], 
                ['Lamb - Leg, Boneless', 'Lamb -', ', Boneless', 'Leg, Bon'], 
                ['Wasabi Paste', 'W', ' Paste', ' Pa'], 
                ['Lidsoupcont Rp12dn', 'Lidsoupco', 'nt Rp12dn', 'nt Rp12dn'], 
                ['Pasta - Cappellini, Dry', 'Pasta - Cap', 'ellini, Dry', 'appellini,'], 
                ['Oil - Margarine', 'Oil -', 'garine', 'rgari'], 
                ['Amaretto', 'A', 'etto', 'Ama'], 
                ['Marzipan 50/50', 'Marzi', 'n 50/50', 'ipan 5'], 
                ['Wine - Sauvignon Blanc', 'Wine ', 'gnon Blanc', 'Wine - Sau'], 
                ['Beef - Striploin', 'Beef -', 'riploin', 'eef - '], 
                ['Pepper - White, Ground', 'Pepper', 'Ground', '-'], 
                ['Veal - Bones', 'V', ' Bones', ' - Bon'], 
                ['Beans - Turtle, Black, Dry', 'Beans', 'ack, Dry', 'Tur'], 
                ['Almonds Ground Blanched', 'A', 'ched', 'round Blan'], 
                ['Wine - Wyndham Estate Bin 777', 'Wine', 'ate Bin 777', 'ine - Wyndham'], 
                ['Beer - Sleemans Honey Brown', 'Beer - Sl', 'Honey Brown', 'er -'], 
                ['Ketchup - Tomato', 'Ketch', 'mato', 'tchup - '], 
                ['Tortillas - Flour, 12', 'Tor', ' Flour, 12', 'l'], 
                ['Sweet Pea Sprouts', 'Swe', 'prouts', 'a Sprou'], 
                ['Bread - Mini Hamburger Bun', 'Bread -', 'r Bun', 'i Hambur'], 
                ['Chocolate Eclairs', 'Chocolate', ' Eclairs', 'Ch'], 
                ['Oil - Shortening - All - Purpose', 'Oil ', '- Purpose', ' - All - Purpo'], 
                ['Chocolate - Milk Coating', 'Ch', 'Coating', 'e - M'], 
                ['Yukon Jack', 'Y', 'Jack', 'n'], 
                ['Saskatoon Berries - Frozen', 'Sask', 'rozen', 'errie'], 
                ['Smoked Paprika', 'Smoke', 'aprika', 'd Pa'], 
                ['Bacardi Breezer - Tropical', 'Bacardi Bre', 'pical', 'rdi'], 
                ['Juice - Propel Sport', 'Juice ', 'el Sport', 'rop'], 
                ['Pants Custom Dry Clean', 'Pants Cus', ' Dry Clean', 'ts Cu'], 
                ['Lid - 10,12,16 Oz', 'Lid', '6 Oz', ' 1'], 
                ['Lamb - Whole, Fresh', 'La', 'e, Fresh', 'ole, Fre'], 
                ['Ice Cream - Vanilla', 'Ice Cr', 'Vanilla', '- Vanilla'], 
                ['Stock - Chicken, White', 'Stoc', ', White', 't'], 
                ['Flour - Rye', 'Fl', '- Rye', 'r - R'], 
                ['Pectin', 'Pe', 'ctin', 'Pec'], 
                ['Muffin - Carrot Individual Wrap', 'Muffin - Carro', 'dividual Wrap', ' Carrot Indiv'], 
                ['Chocolate - Chips Compound', 'Chocolate ', 'ompound', 'hocolate '], 
                ['Sauce - Black Current, Dry Mix', 'S', 'Dry Mix', 'lack '], 
                ['Yogurt - Assorted Pack', 'Yog', ' Pack', 'Yogurt - As'], 
                ['Sugar - Splenda Sweetener', 'Sugar - ', ' Sweetener', ' Splenda Sw'], 
                ['Mushroom - Enoki, Dry', 'Mushroom ', 'ki, Dry', 's'], 
                ['Beef - Shank', 'Bee', ' Shank', '- Sha'], 
                ['Bamboo Shoots - Sliced', 'Bamboo Sho', ' - Sliced', 'oo'], 
                ['Salt And Pepper Mix - White', 'Salt And Pep', '- White', 'epper'], 
                ['Milk - Skim', 'Milk -', 'Skim', 'lk -'], 
                ['Shrimp, Dried, Small / Lb', 'Shrimp, D', ', Small / Lb', ' Dried, Smal'], 
                ['Praline Paste', 'Pral', 'Paste', 'alin'], 
                ['Wine - Magnotta - Belpaese', 'Wine - Magnot', ' - Belpaese', ' M'], 
                ['Myers Planters Punch', 'Myers Plan', ' Punch', 'Myers P'], 
                ['Squeeze Bottle', 'Squee', 'Bottle', 'e Bottl'], 
                ['Wine - Casillero Deldiablo', 'Wine - C', 'ero Deldiablo', 'ne - Casi'], 
                ['Venison - Striploin', 'Veni', 'iploin', ' - Strip'], 
                ['Chef Hat 20cm', 'Chef H', 't 20cm', 'ef'], 
                ['Cape Capensis - Fillet', 'Cape C', 'Fillet', 'pe '], 
                ['Rum - Dark, Bacardi, Black', 'Ru', 'ardi, Black', ', Bacar'], 
                ['Soup - Knorr, Classic Can. Chili', 'Soup - Knor', '. Chili', 'r,'], 
                ['Mushroom - Enoki, Dry', 'Mushroom', 'i, Dry', ' - Enoki,'], 
                ['Dish Towel', 'D', 'Towel', ' Towe'], 
                ['Fish - Artic Char, Cold Smoked', 'Fish ', 'Cold Smoked', 'rtic Cha'], 
                ['Sugar - Icing', 'Su', 'Icing', ' - '], 
                ['Ecolab Digiclean Mild Fm', 'Ecola', 'lean Mild Fm', 'Digiclea'], 
                ['Trout - Hot Smkd, Dbl Fillet', 'Trout ', 'l Fillet', ' Hot '], 
                ['Longos - Assorted Sandwich', 'Longos - ', 'dwich', 'orted San'], 
                ['Sausage - Chorizo', 'Sa', 'rizo', ' - Chor'], 
                ['Water - Mineral, Carbonated', 'Wa', 'rbonated', 'r'], 
                ['Venison - Denver Leg Boneless', 'Venison - Denve', 'Leg Boneless', 'niso'], 
                ['Chicken - Thigh, Bone In', 'Chicke', 'one In', 'Thigh, Bon'], 
                ['Oregano - Dry, Rubbed', 'Oregano -', 'ubbed', 'regano'], 
                ['Puree - Mocha', 'Pur', 'ocha', ' - Moch'], 
                ['Jam - Raspberry', 'J', 'erry', 'am '], 
                ['Nut - Pine Nuts, Whole', 'Nut -', 'uts, Whole', '- Pine '], 
                ['Skirt - 24 Foot', 'Sk', '24 Foot', '- 24'], 
                ['Wine - Chateau Bonnet', 'W', 'au Bonnet', ' C'], 
                ['Pork - Back Ribs', 'Pork ', 'k Ribs', '-'], 
                ['Corn - On The Cob', 'Co', 'e Cob', 'On The C'], 
                ['Salmon - Sockeye Raw', 'Salmon - S', 'ye Raw', 'almo'], 
                ['Cup - 3.5oz, Foam', 'Cup - 3.5', ' Foam', '5oz, F'], 
                ['Wine - Remy Pannier Rose', 'Wine - ', 'annier Rose', ' Panni'], 
                ['Silicone Parch. 16.3x24.3', 'Silicone P', '.3x24.3', 'rch. 1'], 
                ['Otomegusa Dashi Konbu', 'Otome', 'Konbu', 'ashi Konbu'], 
                ['Island Oasis - Ice Cream Mix', 'Island Oasis ', 'ream Mix', 'nd'], 
                ['Saskatoon Berries - Frozen', 'Sas', 'Frozen', 'oon'], 
                ['Beer - True North Lager', 'Beer - ', 'North Lager', 'e'], 
                ['Nantucket - Orange Mango Cktl', 'Nantucket - O', ' Cktl', 'ntu'], 
                ['Tea - Camomele', 'Tea - ', 'momele', 'a'], 
                ['Cookies - Englishbay Wht', 'Co', 'y Wht', 'Cookies - En'], 
                ['Jolt Cola - Electric Blue', 'Jolt', 'ic Blue', ' Cola - El'], 
                ['Wine - White, Riesling, Semi - Dry', 'Wine - Wh', 'ing, Semi - Dry', 'ine - White, Ries'], 
                ['Haggis', 'Ha', 'ggis', 'ggi'], 
                ['Longos - Penne With Pesto', 'Longos - Penn', 'ith Pesto', 'gos - Penn'], 
                ['Carbonated Water - Cherry', 'Carbonated ', '- Cherry', 'ted Water -'], 
                ['Oyster - In Shell', 'Oyster', 'hell', ' In'], 
                ['Beef - Cow Feet Split', 'Be', 'Split', 'Feet Spl'], 
                ['Beef - Striploin Aa', 'Beef - St', 'in Aa', '- Striplo'], 
                ['Lentils - Green, Dry', 'Len', 'n, Dry', 'Green, D'], 
                ['Sole - Fillet', 'S', 'llet', 'F'], 
                ['Energy Drink - Redbull 355ml', 'Energy Drink ', '55ml', 'Drink -'], 
                ['Cookie - Oreo 100x2', 'Cookie - O', ' 100x2', 'Cookie '], 
                ['Food Colouring - Blue', 'Food C', 'Blue', 'ur'], 
                ['Energy Drink Red Bull', 'Energ', 'k Red Bull', 'Energy'], 
                ['Pastry - Lemon Danish - Mini', 'Pa', 'ish - Mini', 'Pastry - L'], 
                ['Bread - Crumbs, Bulk', 'Bread - Cr', ' Bulk', 'Bre'], 
                ['Apples - Spartan', 'App', 'Spartan', ' - Spar'], 
                ['Chicken Breast Wing On', 'Chicken Bre', 'st Wing On', 'Chic'], 
                ['Pork - Caul Fat', 'Por', 'ul Fat', ' '], 
                ['Cleaner - Lime Away', 'Cleaner', 'Lime Away', '-'], 
                ['Wine - Cotes Du Rhone Parallele', 'Wine - C', 'llele', 'tes'], 
                ['Sauce - Demi Glace', 'Sauc', 'i Glace', 'Sau'], 
                ['Beef - Top Sirloin', 'Be', 'rloin', 'eef - To'], 
                ['Ginger - Crystalized', 'Gi', 'stalized', 'er - '], 
                ['Cleaner - Comet', 'Cleaner ', 'omet', 'ean'], 
                ['Mayonnaise - Individual Pkg', 'Mayonn', 'al Pkg', 'Indi'], 
                ['Lime Cordial - Roses', 'Li', ' - Roses', ' Cordial'], 
                ['Cookie Dough - Peanut Butter', 'Cookie', 'ut Butter', 'Doug'], 
                ['Fennel - Seeds', 'Fennel ', 'eeds', 'el '], 
                ['Goulash Seasoning', 'Goulash S', 'asoning', 'oulash'], 
                ['Ham - Black Forest', 'Ham - ', 'rest', 'a'], 
                ['Seedlings - Mix, Organic', 'Seed', 'Organic', 'ings - Mi'], 
                ['Silicone Paper 16.5x24', 'Sili', '.5x24', 'i'], 
                ['Blackberries', 'Bl', 'rries', 'erri'], 
                ['Wine - Peller Estates Late', 'Wine - Pelle', 'tates Late', ' - Peller '], 
                ['Tomato - Plum With Basil', 'Tomat', 'm With Basil', 'lum With '], 
                ['Sauce - Soya, Light', 'Sau', ', Light', ' So'], 
                ['Table Cloth 54x72 Colour', 'T', 'x72 Colour', ' Clot'], 
                ['Cake - Pancake', 'Cake -', 'ncake', 'a'], 
                ['Mushroom - Porcini, Dry', 'Mushroom', ', Dry', 'ush'], 
                ['Wine - Penfolds Koonuga Hill', 'Win', 's Koonuga Hill', ' - Penfolds K'], 
                ['Ecolab - Hobart Upr Prewash Arm', 'Eco', 'rewash Arm', ' - Hob'], 
                ['Egg Patty Fried', 'Egg Pa', ' Fried', 'tty Fr'], 
                ['Jam - Strawberry, 20 Ml Jar', 'Jam - Strawber', ' 20 Ml Jar', ' Strawberry'], 
                ['Sprouts - Baby Pea Tendrils', 'Sprout', ' Tendrils', 'outs - Ba'], 
                ['Green Scrubbie Pad H.duty', 'Green Scrubbi', 'H.duty', 'en Scrub'], 
                ['Yams', 'Y', 'ms', 'ams'], 
                ['Lotus Root', 'Lot', ' Root', 'us Ro'], 
                ['Pasta - Fettuccine, Dry', 'Pasta -', 'ccine, Dry', 'tuccine, Dry'], 
                ['Appetizer - Chicken Satay', 'Appetizer - ', 'icken Satay', ' - '], 
                ['Tarragon - Primerba, Paste', 'Tarrag', 'Paste', '-'], 
                ['Coriander - Seed', 'Corian', 'Seed', 'er - See'], 
                ['Venison - Striploin', 'Veni', 'loin', 'eniso'], 
                ['Bread Base - Toscano', 'Bread Ba', ' - Toscano', 'e - '], 
                ['True - Vue Containers', 'True -', 'Containers', '- '], 
                ['Chicken Breast Halal', 'Chic', 'ast Halal', 'ea'], 
                ['Cheese - Shred Cheddar / Mozza', 'Cheese - Shred', 'Mozza', 'Cheese'], 
                ['Coffee Cup 12oz 5342cd', 'Coffee ', 'z 5342cd', 'offee'], 
                ['Wine - Chateau Bonnet', 'Wine - Chat', 'eau Bonnet', 'ne - Ch'], 
                ['Pepper - Paprika, Spanish', 'P', 'nish', 'pp'], 
                ['Soup - Campbellschix Stew', 'So', ' Stew', 'ampbellschix '], 
                ['Peas - Frozen', 'Peas', 'Frozen', ' - Froz'], 
                ['Juice - Orange 1.89l', 'Juice -', '.89l', 'ange 1.'], 
                ['Creamers - 10%', 'Cre', ' - 10%', 'rs '], 
                ['Pastry - Butterscotch Baked', 'Pastry - Butt', ' Baked', 'try - B'], 
                ['Tomatoes Tear Drop', 'To', ' Drop', 'T'], 
                ['Yoplait Drink', 'Y', 'Drink', 'op'], 
                ['Gooseberry', 'G', 'erry', 'o'], 
                ['Cinnamon - Ground', 'Cinnamo', 'ound', 'Ci'], 
                ['Aspic - Amber', 'A', 'mber', ' - Ambe'], 
                ['Longos - Penne With Pesto', 'Longos ', 'esto', 'enne '], 
                ['Wine - Alsace Riesling Reserve', 'Wine - Al', 'iesling Reserve', 'lsace Riesli'], 
                ['Spring Roll Wrappers', 'Spring Rol', ' Wrappers', 'ring Roll'], 
                ['Cheese - Parmesan Grated', 'Che', 'mesan Grated', 'rmesan Grat'], 
                ['Mushroom - Oyster, Fresh', 'Mus', 'ter, Fresh', 'oom '], 
                ['Salmon Atl.whole 8 - 10 Lb', 'Salmon', 'ole 8 - 10 Lb', ' Atl'], 
                ['Soup V8 Roasted Red Pepper', 'Sou', 'd Pepper', 'oup V8 Roast'], 
                ['Godiva White Chocolate', 'Go', 'hocolate', 'Godiva '], 
                ['Thyme - Lemon, Fresh', 'Thyme ', ', Fresh', 'hyme -'], 
                ['Tofu - Soft', 'Tofu -', 'Soft', 'Tofu '], 
                ['Butter Balls Salted', 'Butte', 'Salted', 'B'], 
                ['Trout - Hot Smkd, Dbl Fillet', 'Trout - Hot S', ' Fillet', '- H'], 
                ['Veal - Leg', 'Veal', ' Leg', 'l -'], 
                ['Chilli Paste, Hot Sambal Oelek', 'Chi', 'l Oelek', ', H'], 
                ['Lid Tray - 16in Dome', 'Lid', ' 16in Dome', ' Tr'], 
                ['Jameson Irish Whiskey', 'Jameson Iri', 'Whiskey', ' I'], 
                ['Flower - Commercial Bronze', 'Flo', 'ercial Bronze', 'ercial Bro'], 
                ['Milkettes - 2%', 'Milk', ' - 2%', 'ket'], 
                ['Wine - Red, Wolf Blass, Yellow', 'Wine - Re', 'lass, Yellow', ', '], 
                ['Beer - Sleemans Cream Ale', 'Beer - Sle', 'am Ale', 'mans Cre'], 
                ['Green Tea Refresher', 'Green', 'esher', 'Tea R'], 
                ['Apples - Spartan', 'App', 'Spartan', 's -'], 
                ['Cloves - Ground', 'Cloves -', 'ound', 'Clove'], 
                ['Dill Weed - Dry', 'Dil', ' Dry', 'll Weed'], 
                ['Chilli Paste, Sambal Oelek', 'C', 'al Oelek', 'lli Paste,'], 
                ['Praline Paste', 'Pralin', ' Paste', 'Pra'], 
                ['Bread - Italian Roll With Herbs', 'Bread - Ita', 'l With Herbs', 'an Ro'], 
                ['Cheese - Cottage Cheese', 'Che', 'e Cheese', ' C'], 
                ['Oven Mitt - 13 Inch', 'Oven', '13 Inch', 't - 13 I'], 
                ['Tea - Jasmin Green', 'Tea ', 'n Green', 'T'], 
                ['Tray - 12in Rnd Blk', 'T', 'd Blk', 'ray - '], 
                ['Mahi Mahi', 'Mahi', 'Mahi', 'Mahi'], 
                ['Beef - Rouladin, Sliced', 'Beef - ', 'din, Sliced', 'Rouladin, S'], 
                ['Pork - Tenderloin, Frozen', 'Pork - Tend', ', Frozen', ' '], 
                ['Sausage - Breakfast', 'Sausag', 'reakfast', ' Breakf'], 
                ['Ecolab - Medallion', 'Ecolab -', 'lion', ' - Me'], 
                ['Sour Puss Raspberry', 'Sou', 'spberry', 'r Puss '], 
                ['Samosa - Veg', 'S', '- Veg', 'sa '], 
                ['Cookies Cereal Nut', 'C', ' Nut', 'e'], 
                ['Pie Filling - Pumpkin', 'Pie F', 'umpkin', 'e F'], 
                ['Cookie - Dough Variety', 'Cookie -', 'Variety', 'ookie'], 
                ['Wine - Carmenere Casillero Del', 'Wine - Carmene', 'e Casillero Del', 'e - C'], 
                ['Bread - Crumbs, Bulk', 'Bread - Cr', 's, Bulk', 'Crumbs, '], 
                ['Ham - Virginia', 'Ham - ', 'ginia', 'am - Vi'], 
                ['Kellogs Raisan Bran Bars', 'Kellogs Rai', 'Bars', 'isan '], 
                ['Longos - Grilled Veg Sandwiches', 'Lon', 'wiches', 'led V'], 
                ['Salt - Celery', 'Sal', 'lery', 'alt '], 
                ['Ecolab - Power Fusion', 'Ecolab', 'usion', 'ab '], 
                ['Thermometer Digital', 'Therm', 'gital', 'Thermom'], 
                ['Sauce - Soy Low Sodium - 3.87l', 'Sauce', 'um - 3.87l', ' Soy Low '], 
                ['Mushroom - Porcini Frozen', 'Mu', 'ozen', '- Porcini Fro'], 
                ['Rhubarb', 'Rh', 'barb', 'Rh'], 
                ['Bagelers', 'Ba', 'lers', 'a'], 
                ['Green Tea Refresher', 'G', 'resher', ' Refres'], 
                ['Beer - True North Strong Ale', 'Beer - Tru', 'ong Ale', 'True Nort'], 
                ['Lumpfish Black', 'L', 'lack', 'mpf'], 
                ['Butter - Salted', 'Bu', ' Salted', 'tter - S'], 
                ['Rootbeer', 'R', 'beer', 'be'], 
                ['Uniform Linen Charge', 'Unifor', 'arge', 'rm Linen'], 
                ['Pasta - Tortellini, Fresh', 'Pasta -', 'llini, Fresh', 'Pasta - Tort'], 
                ['Beans - Kidney White', 'Beans - Ki', 'ey White', ' Kidn'], 
                ['Cut Wakame - Hanawakaba', 'Cut Wakame -', 'Hanawakaba', 'me - Han'], 
                ['Lid Coffeecup 12oz D9542b', 'L', '9542b', 'cup 12o'], 
                ['Potatoes - Parissienne', 'Potatoes ', 'ssienne', 'es - P'], 
                ['Apple - Fuji', 'App', '- Fuji', 'le -'], 
                ['Appetizer - Mini Egg Roll, Shrimp', 'Appetize', 'hrimp', ' - Mini Egg '], 
                ['Beef - Rib Roast, Cap On', 'Be', 'ast, Cap On', 'b'], 
                ['Anchovy In Oil', 'Anchovy', 'In Oil', 'hovy '], 
                ['Cheese - Manchego, Spanish', 'Cheese ', 'go, Spanish', ' - Ma'], 
                ['Pastry - Choclate Baked', 'Pastry ', 'Baked', 'y - Chocl'], 
                ['Bread Bowl Plain', 'Bread Bo', ' Plain', 'wl Plai'], 
                ['Coffee Beans - Chocolate', 'C', 'hocolate', 'e Beans '], 
                ['Oil - Peanut', 'Oil - ', 'anut', ' - P'], 
                ['Sachet', 'Sac', 'chet', 'c'], 
                ['Cookie Choc', 'Cooki', ' Choc', 'kie C'], 
                ['Jameson - Irish Whiskey', 'Jameson -', ' Whiskey', '-'], 
                ['Oil - Coconut', 'Oil - ', 'conut', 'oconut'], 
                ['Cookies - Amaretto', 'Cookies -', 'aretto', 'ookies - '], 
                ['Daikon Radish', 'Daikon ', 'adish', 'on Ra'], 
                ['Pork - Sausage, Medium', 'Pork - Saus', ' Medium', 'ork - '], 
                ['Duck - Fat', 'Duc', '- Fat', '- Fa'], 
                ['Beef - Short Ribs', 'Beef - Sh', 'rt Ribs', 'ort Ribs'], 
                ['Sesame Seed', 'Sesame', 'Seed', 'sam'], 
                ['Nut - Pine Nuts, Whole', 'Nut - Pin', 'hole', 'e'], 
                ['Barramundi', 'Ba', 'mundi', 'a'], 
                ['Gatorade - Orange', 'Gatora', 'ange', 'rade -'], 
                ['Potatoes - Idaho 100 Count', 'Potato', 'ho 100 Count', ' Ida'], 
                ['Wheat - Soft Kernal Of Wheat', 'Wheat - Soft', 'rnal Of Wheat', 'Wheat -'], 
                ['Wine - Lou Black Shiraz', 'Wine - ', ' Shiraz', 'Lou'], 
                ['Cookies Almond Hazelnut', 'Cookies Alm', 'elnut', 'lmond Haz'], 
                ['Mustard - Seed', 'Mus', 'Seed', 'ustard'], 
                ['Carrots - Mini, Stem On', 'Carrot', 'i, Stem On', 'Carrots - '], 
                ['Garam Marsala', 'Garam ', 'rsala', 'm'], 
                ['Napkin White - Starched', 'Napk', '- Starched', 'hite - Sta'], 
                ['Crush - Grape, 355 Ml', 'Cr', '55 Ml', '- Grape, 3'], 
                ['Wine - Red, Lurton Merlot De', 'Wine - ', 'lot De', 'ed, L'], 
                ['Flour - Whole Wheat', 'Flour - W', 'le Wheat', 'Flour -'], 
                ['Goat - Whole Cut', 'Goat - W', 'le Cut', 'at'], 
                ['Lettuce - Boston Bib', 'Lett', 'ton Bib', 'u'], 
                ['Wine - Red, Antinori Santa', 'Wine -', 'Santa', '- Red, Anti'], 
                ['Bagelers - Cinn / Brown Sugar', 'Bagelers - Ci', '/ Brown Sugar', ' - '], 
                ['Beans - Black Bean, Preserved', 'Beans ', 'an, Preserved', ' Black Be'], 
                ['Worcestershire Sauce', 'Wor', 'auce', 'ers'], 
                ['Appetizer - Southwestern', 'Appeti', 'western', 'Appetizer - '], 
                ['Gelatine Leaves - Bulk', 'G', '- Bulk', 'atin'], 
                ['Cookie Dough - Chocolate Chip', 'Cookie ', 'late Chip', 'o'], 
                ['Croissants Thaw And Serve', 'Croissants ', 'erve', 'Thaw'], 
                ['Wine - Fat Bastard Merlot', 'Wine - Fat ', ' Merlot', 't Basta'], 
                ['Island Oasis - Cappucino Mix', 'Isla', 'ino Mix', 'sis - '], 
                ['Chocolate - Milk Coating', 'Chocola', 'lk Coating', 'oco'], 
                ['Wine - Stoneliegh Sauvignon', 'Wi', 'egh Sauvignon', 'e -'], 
                ['Pork - Back Ribs', 'Pork', 'ck Ribs', '- Back'], 
                ['Sandwich Wrap', 'Sandwi', ' Wrap', 'dwich '], 
                ['Puff Pastry - Slab', 'P', 'Slab', ' Past'], 
                ['Juice - Ocean Spray Cranberry', 'Juice', 'berry', 'n Spray Cran'], 
                ['Steampan - Foil', 'Stea', 'Foil', 'Steam'], 
                ['Beer - Blue Light', 'Bee', ' Light', '- Bl'], 
                ['Water - Spring Water, 355 Ml', 'Water - Sprin', '355 Ml', ' Water, 355 '], 
                ['Milk - Skim', 'M', ' Skim', 'ilk - '], 
                ['Bread Bowl Plain', 'Brea', 'Plain', 'ad B'], 
                ['Breakfast Quesadillas', 'Breakfas', 'illas', 'akfa'], 
                ['Brownies - Two Bite, Chocolate', 'Brownies - Two', 'hocolate', ' '], 
                ['Wine - Red, Cabernet Merlot', 'Wine - R', 'et Merlot', ', Caber'], 
                ['Nut - Peanut, Roasted', 'Nut - Peanu', ', Roasted', 'Nut - Peanu'], 
                ['Schnappes Peppermint - Walker', 'S', 'lker', 'pper'], 
                ['Ostrich - Prime Cut', 'Ost', ' Cut', 'Prime Cut'], 
                ['Wine - Montecillo Rioja Crianza', 'Wine ', ' Rioja Crianza', 'cillo Rioja '], 
                ['Ice Cream - Fudge Bars', 'Ice ', 'udge Bars', 'am - Fudge '], 
                ['Zucchini - Yellow', 'Zu', 'ellow', 'Zucchini'], 
                ['Leeks - Baby, White', 'Leeks - B', 'White', ' '], 
                ['Pears - Fiorelle', 'P', 'relle', ' Fior'], 
                ['Pork - Shoulder', 'Po', 'oulder', 'houlder'], 
                ['Beef - Kobe Striploin', 'Beef -', 'iploin', ' Ko'], 
                ['Yeast Dry - Fleischman', 'Yeast Dr', 'eischman', ' - Fleis'], 
                ['Sausage - Meat', 'Sausa', ' - Meat', ' - '], 
                ['Beans - Yellow', 'Beans ', ' Yellow', ' Yel'], 
                ['Country Roll', 'Countr', 'y Roll', 'ry Rol'], 
                ['Boogies', 'Bo', 'ies', 'gie'], 
                ['Pea - Snow', 'Pea ', ' Snow', ' '], 
                ['Mousse - Mango', 'Mouss', '- Mango', 'e - Ma'], 
                ['Bread - Bagels, Plain', 'Bre', ' Plain', 'agels, '], 
                ['Beans - Green', 'Bea', 'Green', 'eans - '], 
                ['Grenadine', 'G', 'dine', 'n'], 
                ['French Pastries', 'Fre', 'astries', 'rench P'], 
                ['Table Cloth 53x69 White', 'Ta', 'x69 White', 'ble Clot'], 
                ['Sugar - Fine', 'Sugar', 'Fine', 'uga'], 
                ['Bag - Regular Kraft 20 Lb', 'Bag -', 'ft 20 Lb', 'ag - Regul'], 
                ['Coffee - Hazelnut Cream', 'Co', ' Cream', 'elnut Cream'], 
                ['Cheese - Valancey', 'Cheese', 'ancey', 'Chees'], 
                ['Beef - Top Sirloin - Aaa', 'Beef - Top ', ' - Aaa', 'eef - Top S'], 
                ['Soup - Beef, Base Mix', 'Soup - Be', 'e Mix', ' '], 
                ['Tofu - Firm', 'Tof', ' Firm', 'fu - F'], 
                ['Scampi Tail', 'Scampi', 'Tail', 'i '], 
                ['Lamb - Racks, Frenched', 'Lamb', 'renched', 's, Frenc'], 
                ['Crab - Soft Shell', 'Crab -', 'hell', ' So'], 
                ['Oven Mitt - 13 Inch', 'Oven Mitt ', '- 13 Inch', 'itt '], 
                ['Water - Mineral, Carbonated', 'Wat', 'bonated', 'l'], 
                ['Jicama', 'Ji', 'cama', 'ama'], 
                ['Wine - Merlot Vina Carmen', 'Win', ' Vina Carmen', 't Vina C'], 
                ['Iced Tea Concentrate', 'Ic', 'ntrate', ' Conc'], 
                ['Cod - Black Whole Fillet', 'Cod ', 'Whole Fillet', 'd'], 
                ['Rum - Coconut, Malibu', 'Rum - Cocon', 't, Malibu', 'Coconut'], 
                ['Anisette - Mcguiness', 'Anisette -', 'Mcguiness', ' - Mcgu'], 
                ['Ginger - Pickled', 'Ginger -', 'kled', '-'], 
                ['Chicken - Thigh, Bone In', 'Chicken - T', 'Bone In', ' - Thig'], 
                ['Brownies - Two Bite, Chocolate', 'Brown', 'ite, Chocolate', ' Two Bi'], 
                ['Wine - Sogrape Mateus Rose', 'Wine - Sogra', 's Rose', 'e'], 
                ['Filling - Mince Meat', 'Filling', ' Meat', ' Mi'], 
                ['Cherries - Maraschino,jar', 'Cher', 'aschino,jar', ' - Mar'], 
                ['Cauliflower', 'Cauli', 'lower', 'iflo'], 
                ['Jam - Strawberry, 20 Ml Jar', 'Jam - ', 'ry, 20 Ml Jar', 'rawber'], 
                ['Lentils - Red, Dry', 'Le', 'ed, Dry', ' - Red, D'], 
                ['Pepper - Green, Chili', 'Pepper - Gr', 'een, Chili', ' - Green,'], 
                ['Wine - Red, Harrow Estates, Cab', 'Wine - Red, H', ' Estates, Cab', ', Harrow Esta'], 
                ['Ecolab - Orange Frc, Cleaner', 'E', 'rc, Cleaner', 'olab - '], 
                ['Muffin Puck Ww Carrot', 'Muffin Pu', 'rrot', 'n Puc'], 
                ['Paste - Black Olive', 'P', 'ck Olive', 'Paste'], 
                ['Lemons', 'Lem', 'ons', 'mo'], 
                ['Browning Caramel Glace', 'Browning C', 'lace', 'wning'], 
                ['Kellogs Raisan Bran Bars', 'Kellogs ', 'n Bran Bars', 'logs'], 
                ['Plate Foam Laminated 9in Blk', 'Plate Foam La', 'ed 9in Blk', 'Laminated '], 
                ['Wine - Pinot Noir Mondavi Coastal', 'W', 'avi Coastal', 'oir Mon'], 
                ['Puree - Pear', 'Puree ', '- Pear', 'Puree '], 
                ['Cattail Hearts', 'Cattai', 'arts', ' Hear'], 
                ['Beef Dry Aged Tenderloin Aaa', 'Beef Dry Age', 'oin Aaa', 'y '], 
                ['Crackers - Trio', 'C', ' Trio', 'kers - T'], 
                ['Pepperoni Slices', 'Pe', 'Slices', 'ni Sli'], 
                ['Soup - Campbells, Lentil', 'Sou', ' Lentil', 'bells, Lent'], 
                ['Lid - 10,12,16 Oz', 'Lid - 1', '2,16 Oz', '- 10,12,1'], 
                ['Appetizer - Asian Shrimp Roll', 'Appetizer -', 'Roll', 'petizer'], 
                ['Bread - White Mini Epi', 'Bread - W', 'ni Epi', 'hite Mini E'], 
                ['Pail For Lid 1537', 'Pai', '1537', 'l For '], 
                ['Sproutsmustard Cress', 'Sprou', 'ress', 'r'], 
                ['Milk 2% 500 Ml', 'Milk ', '0 Ml', 'lk'], 
                ['Oil - Olive Bertolli', 'Oil - Oli', ' Bertolli', ' - O'], 
                ['Edible Flower - Mixed', 'E', ' Mixed', 'l'], 
                ['Sugar - Sweet N Low, Individual', 'Sugar - Sweet N', 'dividual', 'gar '], 
                ['Numi - Assorted Teas', 'Numi ', 'orted Teas', 'so'], 
                ['Lemonade - Black Cherry, 591 Ml', 'Lemonade - B', 'herry, 591 Ml', 'emonade - '], 
                ['Sandwich Wrap', 'Sandw', 'Wrap', 'dwic'], 
                ['Pork - Back, Short Cut, Boneless', 'Pork - Back, Sh', 't, Boneless', '- Ba'], 
                ['Bread - Bistro White', 'B', 'o White', 'istro '], 
                ['Tea Leaves - Oolong', 'Tea', ' Oolong', ' Leaves - '], 
                ['Cranberry Foccacia', 'Cranberr', 'acia', 'Cra'], 
                ['Onions - Spanish', 'Oni', 'anish', 'ns '], 
                ['Chick Peas - Canned', 'C', 'nned', 'Chick '], 
                ['Tea - Herbal Sweet Dreams', 'Tea - ', 'eet Dreams', 'Herbal Swe'], 
                ['Wine - Spumante Bambino White', 'Wine', 'White', 'nte Bambi'], 
                ['Brownies - Two Bite, Chocolate', 'Brownies - Two', 'olate', 'Two Bit'], 
                ['Lettuce - Iceberg', 'Lettu', 'eberg', 'uce '], 
                ['Pail For Lid 1537', 'Pail For ', 'id 1537', ' Lid 15'], 
                ['Okra', 'O', 'kra', 'ra'], 
                ['Guava', 'G', 'va', 'Gu'], 
                ['Table Cloth - 53x69 Colour', 'Table C', 'lour', 'Tabl'], 
                ['Table Cloth 62x120 Colour', 'Table C', 'Colour', 'loth '], 
                ['Spice - Montreal Steak Spice', 'Spice - Montr', 'l Steak Spice', 'Spice'], 
                ['Squid U5 - Thailand', 'S', 'iland', '5 -'], 
                ['Oil - Shortening - All - Purpose', 'Oil - Shor', 'pose', ' - S'], 
                ['White Baguette', 'White B', 'aguette', 'te B'], 
                ['Miso Paste White', 'Miso Pas', 'te White', 'te White'], 
                ['Cabbage - Green', 'Cab', 'Green', 'a'], 
                ['Berry Brulee', 'Berr', 'rulee', 'ry Br'], 
                ['Chips - Assorted', 'Chips', 'rted', ' - Assor'], 
                ['Apple - Custard', 'Apple', 'tard', '- Custar'], 
                ['Eel Fresh', 'E', 'resh', ' Fr'], 
                ['Sauce Tomato Pouch', 'S', 'ouch', 'ma'], 
                ['Coconut - Shredded, Sweet', 'Coconut', ' Sweet', ' - Shred'], 
                ['The Pop Shoppe - Root Beer', 'The P', 't Beer', 'p Shoppe - Ro'], 
                ['Muffin Mix - Banana Nut', 'M', 'na Nut', 'in Mix - B'], 
                ['Muffins - Assorted', 'Muffins -', 'Assorted', ' - As'], 
                ['Mahi Mahi', 'M', 'Mahi', 'Mahi '], 
                ['Nut - Cashews, Whole, Raw', 'Nut - Cashe', ', Whole, Raw', 'hews, Whole,'], 
                ['Bag Stand', 'Bag S', 'tand', 'g'], 
                ['Napkin - Cocktail,beige 2 - Ply', 'Napkin - Cock', 'ge 2 - Ply', 'in -'], 
                ['Cake - French Pear Tart', 'Cake - F', ' Tart', 'e'], 
                ['Tea - Jasmin Green', 'Tea - J', 'Green', 'Tea - Ja'], 
                ['Momiji Oroshi Chili Sauce', 'Momiji Oro', 'Chili Sauce', 'i Chili Sauc'], 
                ['Walkers Special Old Whiskey', 'Walkers', ' Whiskey', 'cial Old Whis'], 
                ['Wine - Port Late Bottled Vintage', 'Wine - Por', 'Bottled Vintage', '- Port Lat'], 
                ['Sauce - Black Current, Dry Mix', 'Sauce - Bl', 'nt, Dry Mix', 'ack Curren'], 
                ['Lettuce - Sea / Sea Asparagus', 'Lettuce - S', 'ea Asparagus', 'Sea / Sea A'], 
                ['Bamboo Shoots - Sliced', 'Bamboo ', '- Sliced', 'oo Shoo'], 
                ['Cabbage Roll', 'Cabba', 'e Roll', 'age '], 
                ['Lemonade - Natural, 591 Ml', 'Lemonade - N', ' 591 Ml', 'monade'], 
                ['Brandy - Bar', 'Bra', ' Bar', 'Br'], 
                ['Lemonade - Natural, 591 Ml', 'Lemonad', '1 Ml', 'de - Natural'], 
                ['Bar Mix - Pina Colada, 355 Ml', 'Bar Mix - P', 'lada, 355 Ml', 'Pina Colada, '], 
                ['Everfresh Products', 'E', 'Products', 'Ever'], 
                ['Spinach - Frozen', 'Spi', 'ozen', 'h '], 
                ['Snails - Large Canned', 'Snails', 'e Canned', 'Snails '], 
                ['Shallots', 'Sh', 'lots', 'Shal'], 
                ['Calypso - Black Cherry Lemonade', 'Calypso ', 'onade', 'alypso - '], 
                ['Coffee - Almond Amaretto', 'Coffee -', 'etto', 'mo'], 
                ['Vinegar - Raspberry', 'Vinegar - ', 'berry', 'negar'], 
                ['Sloe Gin - Mcguinness', 'Sloe G', 'nness', 'e Gin - M'], 
                ['Sugar - Crumb', 'Sug', 'Crumb', ' Crumb'], 
                ['Bread - Olive Dinner Roll', 'B', 'nner Roll', ' Dinner Ro'], 
                ['Seabream Whole Farmed', 'Seab', 'e Farmed', 'hole'], 
                ['Ham - Proscuitto', 'Ha', 'oscuitto', '- Pro'], 
                ['Asparagus - White, Fresh', 'As', ', Fresh', 'Asparagus -'], 
                ['Sugar - Invert', 'Suga', ' Invert', ' Invert'], 
                ['Yeast Dry - Fleischman', 'Y', 'ischman', 'ry -'], 
                ['Muffin - Mix - Strawberry Rhubarb', 'Muffin - Mix - ', 'barb', 'fin - Mix '], 
                ['Muffin Mix - Chocolate Chip', 'Muffin Mix - C', 'late Chip', 'fin Mix - Choc'], 
                ['Wine - Pinot Noir Stoneleigh', 'Wine - Pino', 'oneleigh', ' - Pino'], 
                ['Beer - Guiness', 'Bee', 'Guiness', 'r'], 
                ['Grapefruit - White', 'Grap', ' - White', 'ruit - '], 
                ['Pate - Cognac', 'Pat', 'ognac', 'ate -'], 
                ['Broom - Corn', 'Broo', ' Corn', 'Broom '], 
                ['Lamb - Whole Head Off', 'Lamb', 'd Off', 'mb '], 
                ['Container - Foam Dixie 12 Oz', 'Container - ', '2 Oz', 'am Dixie'], 
                ['Pants Custom Dry Clean', 'Pants C', 'lean', 'tom Dry Cle'], 
                ['Bread Base - Gold Formel', 'Brea', 'old Formel', 'ad'], 
                ['Nori Sea Weed - Gold Label', 'Nori Sea W', 'd Label', 'i Sea Weed -'], 
                ['Peas Snow', 'P', 'Snow', 'Peas'], 
                ['Hagen Daza - Dk Choocolate', 'Hag', 'late', 'Hagen'], 
                ['Veal - Chops, Split, Frenched', 'V', ', Frenched', 'al - Chops'], 
                ['Spring Roll Wrappers', 'Spring Rol', ' Wrappers', 'ing Rol'], 
                ['Veal - Inside, Choice', 'V', 'de, Choice', 'eal -'], 
                ['Milk 2% 500 Ml', 'Milk 2%', '00 Ml', ' 500 Ml'], 
                ['Graham Cracker Mix', 'Graham C', 'ker Mix', ' Crac'], 
                ['Energy Drink - Redbull 355ml', 'Energy Drink', 'bull 355ml', ' - Redbull '], 
                ['Gatorade - Orange', 'Gatorad', 'Orange', 'rade -'], 
                ['Ice Cream Bar - Drumstick', 'Ice Cream Ba', 'Drumstick', 'e Cream Bar '], 
                ['Table Cloth 54x54 White', 'Table Cl', '4 White', 'Cloth 54x54 '], 
                ['Sauce - Hollandaise', 'Sauce -', 'aise', 'llandais'], 
                ['Pepper - Chilli Seeds Mild', 'Pe', 'ds Mild', 'r '], 
                ['Pie Filling - Pumpkin', 'Pie Fil', 'pkin', 'ing'], 
                ['Plasticspoonblack', 'Plast', 'black', 'c'], 
                ['Lamb - Pieces, Diced', 'Lamb - Pie', 's, Diced', '- P'], 
                ['Chestnuts - Whole,canned', 'Ches', 'canned', ' -'], 
                ['Beans - Soya Bean', 'Beans', 'Bean', 'Soy'], 
                ['Butter Balls Salted', 'Bu', 's Salted', 'ter Balls'], 
                ['Wine - Montecillo Rioja Crianza', 'Wine - Mon', 'rianza', 'lo Rioja Crianza'], 
                ['Thyme - Dried', 'Thyme ', 'ried', 'me '], 
                ['V8 - Vegetable Cocktail', 'V8', ' Cocktail', '- '], 
                ['Oneshot Automatic Soap System', 'Oneshot ', 'oap System', 'ot Automa'], 
                ['Clams - Bay', 'Clams', '- Bay', 'l'], 
                ['Sauce - Alfredo', 'Sauce -', 'lfredo', 'a'], 
                ['Apple - Macintosh', 'A', 'cintosh', ' Macintos'], 
                ['Garbage Bags - Clear', 'Ga', 'gs - Clear', 'age B'], 
                ['Pork - Bones', 'P', ' Bones', '-'], 
                ['Veal - Slab Bacon', 'Veal - Sl', 'acon', 'ea'], 
                ['Bread Crumbs - Panko', 'Br', 'anko', ' C'], 
                ['Beef - Shank', 'Be', ' Shank', 'eef -'], 
                ['Asparagus - White, Canned', 'Asparagus', 'hite, Canned', 's'], 
                ['Ginger - Ground', 'Ginger', ' Ground', 'Ginge'], 
                ['Chocolate - Pistoles, Lactee, Milk', 'Chocolate ', 'Milk', 'hocola'], 
                ['Salad Dressing', 'Salad ', 'ressing', 'ressi'], 
                ['Wine - Ice Wine', 'Wi', 'Wine', ' - Ice '], 
                ['Wine - White, Lindemans Bin 95', 'Wine', 'ndemans Bin 95', 'e, Lindem'], 
                ['Cookie Dough - Double', 'Co', 'Double', 'g'], 
                ['Veal - Inside', 'Ve', 'nside', 'eal - I'], 
                ['Cheese - La Sauvagine', 'Cheese -', ' Sauvagine', 'se - La'], 
                ['Wine - Alsace Riesling Reserve', 'Wine - Alsace ', 'erve', ' Ri'], 
                ['Apricots - Halves', 'Apri', ' Halves', ' - Ha'], 
                ['Tart Shells - Sweet, 4', 'Tart Shell', ' Sweet, 4', 's -'], 
                ['Doilies - 10, Paper', 'Doilies', ', Paper', '10'], 
                ['Sausage - Liver', 'Sa', '- Liver', 'ge'], 
                ['Pepper - White, Ground', 'Pepper -', 'ound', ' White, G'], 
                ['Pork - Back Ribs', 'Pork -', 'k Ribs', 'Back R'], 
                ['Wine - Baron De Rothschild', 'Wine - Baron', ' Rothschild', 'n'], 
                ['Lettuce - California Mix', 'Lettuce', ' Mix', ' - Cal'], 
                ['Slt - Individual Portions', 'Slt - In', 'Portions', ' - Indi'], 
                ['Chocolate - Liqueur Cups With Foil', 'Chocolate - Li', 'Foil', 'o'], 
                ['Sugar - Brown, Individual', 'Sugar - Brown', 'idual', '- Brown, Ind'], 
                ['Oil - Shortening,liqud, Fry', 'Oil - Shorten', 'g,liqud, Fry', 'n'], 
                ['Pork - Loin, Bone - In', 'Pork - L', ' - In', 'ork - '], 
                ['Tuna - Canned, Flaked, Light', 'Tuna - ', ', Light', ', F'], 
                ['Wine - Montecillo Rioja Crianza', 'Wine - Montecil', 'anza', 'tecillo Rio'], 
                ['Bread - 10 Grain', 'Bread -', 'Grain', 'Br'], 
                ['Tomatoes - Vine Ripe, Red', 'Tomato', 'ne Ripe, Red', '- Vin'], 
                ['Pasta - Cappellini, Dry', 'Past', ' Dry', 'pe'], 
                ['Beef - Kobe Striploin', 'Beef', 'loin', 'f - Kob'], 
                ['Raisin - Dark', 'Raisin', ' Dark', 'aisin'], 
                ['Snapple - Mango Maddness', 'Snapp', 'dness', 'pple - Man'], 
                ['Milk - Condensed', 'Milk - C', 'ensed', ' Conden'], 
                ['Bok Choy - Baby', 'B', ' Baby', 'k C'], 
                ['Coffee - 10oz Cup 92961', 'Coffee - ', ' 92961', ' 10oz C'], 
                ['Chinese Foods - Cantonese', 'Chine', 'nese', 'e Foo'], 
                ['Cheese - Brie, Cups 125g', 'Chee', ' Cups 125g', 'rie, Cups 12'], 
                ['Bread - Rosemary Focaccia', 'Bread - Ro', 'ocaccia', 'o'], 
                ['Olives - Green, Pitted', 'Oli', ' Pitted', ' Green,'], 
                ['Sword Pick Asst', 'Sw', 'k Asst', 'o'], 
                ['Cheese - Mix', 'Ch', ' Mix', 'ees'], 
                ['Chocolate Liqueur - Godet White', 'Chocolate Li', ' Godet White', 'olate Liqueur - '], 
                ['Cake Slab', 'Cake ', 'Slab', 'ake S'], 
                ['Bread - Kimel Stick Poly', 'Brea', 'k Poly', 'd - Kimel St'], 
                ['Broom - Angled', 'Br', ' Angled', 'm'], 
                ['Cake - Dulce De Leche', 'C', 'De Leche', 'ke - D'], 
                ['Juice - Lime', 'Juic', ' Lime', ' - '], 
                ['Hog / Sausage Casing - Pork', 'Hog / ', 'ng - Pork', 'Sa'], 
                ['Wine - Red, Pinot Noir, Chateau', 'Wi', 'Chateau', ' Pinot'], 
                ['Cookies - Amaretto', 'Cookies -', 'Amaretto', ' Ama'], 
                ['Flour - Whole Wheat', 'Flour', 'le Wheat', ' Whol'], 
                ['Octopus - Baby, Cleaned', 'Octop', 'y, Cleaned', 'ct'], 
                ['Triple Sec - Mcguinness', 'T', 'uinness', ' - '], 
                ['Yogurt - Cherry, 175 Gr', 'Yogurt', 'y, 175 Gr', ' - '], 
                ['Contreau', 'Cont', 'reau', 'trea'], 
                ['Pie Filling - Apple', 'Pie F', ' Apple', 'Filling - '], 
                ['Bread - Rye', 'B', ' Rye', 'ead'], 
                ['Steampan Lid', 'St', 'n Lid', 'Steam'], 
                ['Island Oasis - Banana Daiquiri', 'Island Oasis ', 'ana Daiquiri', 'nd'], 
                ['Truffle Cups - Red', 'Tr', ' Red', 'Truffle'], 
                ['Passion Fruit', 'Pas', ' Fruit', ' Frui'], 
                ['Apron', 'Ap', 'pron', 'Ap'], 
                ['Soup Knorr Chili With Beans', 'Soup Knorr C', 'th Beans', 'p Knorr Chil'], 
                ['Amarula Cream', 'Am', 'ream', 'la '], 
                ['Fish - Artic Char, Cold Smoked', 'Fish - Artic ', 'r, Cold Smoked', ' Artic Char, C'], 
                ['Tomatoes - Vine Ripe, Red', 'To', ' Red', 'atoes - Vine'], 
                ['Lid Coffee Cup 8oz Blk', 'Lid ', 'up 8oz Blk', ' Coffe'], 
                ['Galliano', 'G', 'iano', 'Gall'], 
                ['Cabbage - Green', 'Cabbage', '- Green', 'abba'], 
                ['Latex Rubber Gloves Size 9', 'L', 'ze 9', 'bbe'], 
                ['Icecream - Dstk Strw Chseck', 'Icecre', 'w Chseck', ' '], 
                ['Extract - Lemon', 'Ex', '- Lemon', 'xt'], 
                ['Cheese - Grana Padano', 'Ch', ' Padano', 'se '], 
                ['Pie Filling - Apple', 'Pie F', ' - Apple', 'g - A'], 
                ['Pasta - Penne, Lisce, Dry', 'Pasta -', 'sce, Dry', 'e, Lisce, Dry'], 
                ['Pancetta', 'P', 'etta', 'Pan'], 
                ['Ham - Cooked Bayonne Tinned', 'Ham - Cook', 'Tinned', ' Bayonn'], 
                ['Wine - Kwv Chenin Blanc South', 'Wine - Kwv ', 'Blanc South', ' Chenin '], 
                ['Wine - Red, Mosaic Zweigelt', 'Wine', 'ic Zweigelt', 'i'], 
                ['Brandy Cherry - Mcguinness', 'Bran', 'uinness', ' Cherry - M'], 
                ['Jolt Cola - Electric Blue', 'Jolt Cola - E', 'ric Blue', 'ola - Ele'], 
                ['Sobe - Tropical Energy', 'Sobe -', 'l Energy', ' Tr'], 
                ['Sauce - Roasted Red Pepper', 'Sauce - Roa', ' Pepper', 'uce - Ro'], 
                ['Cape Capensis - Fillet', 'Cape', 'llet', 'Cape Ca'], 
                ['Bread - Italian Sesame Poly', 'Bread', ' Sesame Poly', 'lian'], 
                ['Wine - Trimbach Pinot Blanc', 'Wine - Tr', 'not Blanc', 'ne - Trimb'], 
                ['Papadam', 'P', 'adam', 'apad'], 
                ['Mop Head - Cotton, 24 Oz', 'Mop Head ', 'n, 24 Oz', ' '], 
                ['Wine - Chateauneuf Du Pape', 'Wi', 'Du Pape', 'auneuf'], 
                ['Sour Puss Sour Apple', 'So', 'Apple', 'ss S'], 
                ['Cornflakes', 'Cor', 'lakes', 'rnfl'], 
                ['Godiva White Chocolate', 'Godi', 'ocolate', 'diva Whit'], 
                ['Coriander - Ground', 'Cori', '- Ground', 'iander'], 
                ['Pineapple - Regular', 'P', 'Regular', '- Regular'], 
                ['Beef - Striploin Aa', 'Beef - Str', 'iploin Aa', 'iploin Aa'], 
                ['Oil - Shortening,liqud, Fry', 'Oil - Shor', 'liqud, Fry', 'Shorte'], 
                ['Pie Shells 10', 'Pie She', 'lls 10', 'lls 10'], 
                ['Soup Knorr Chili With Beans', 'Soup K', 'Beans', 'li'], 
                ['Chocolate - Compound Coating', 'Chocol', 'mpound Coating', ' Compoun'], 
                ['Venison - Ground', 'Venis', ' Ground', 'n - Gr'], 
                ['Wine La Vielle Ferme Cote Du', 'Wine La Vi', 'erme Cote Du', 'l'], 
                ['Chocolate Bar - Reese Pieces', 'Choco', '- Reese Pieces', ' Bar - '], 
                ['Tart Shells - Savory, 3', 'Tart', 'vory, 3', 'ells -'], 
                ['The Pop Shoppe - Cream Soda', 'The ', 'am Soda', 'p S'], 
                ['Cape Capensis - Fillet', 'Cape Cape', ' - Fillet', 'ensis'], 
                ['Huck Towels White', 'Huck To', 'White', 'k Towels'], 
                ['Kirsch - Schloss', 'Ki', ' Schloss', 'sch - '], 
                ['Ginger - Ground', 'Ging', 'round', 'r - G'], 
                ['Salt - Seasoned', 'Salt -', 'oned', 'easo'], 
                ['Walkers Special Old Whiskey', 'Walke', 'iskey', 'ial Old Whi'], 
                ['Lettuce - Baby Salad Greens', 'Lettuce - Ba', 'ad Greens', 'ttuce - '], 
                ['Lamb Rack Frenched Australian', 'Lamb Rack ', 'lian', 'renched Aus'], 
                ['Wine - Coteaux Du Tricastin Ac', 'Wine ', 'astin Ac', '- Coteaux Du '], 
                ['Wine - Alicanca Vinho Verde', 'Wine - Ali', ' Vinho Verde', ' -'], 
                ['Bread Crumbs - Panko', 'Br', '- Panko', 'Bread Crum'], 
                ['Yucca', 'Y', 'ucca', 'c'], 
                ['Spice - Greek 1 Step', 'Sp', ' 1 Step', ' -'], 
                ['Alize Sunset', 'Al', 'nset', 'lize S'], 
                ['Blueberries - Frozen', 'Blue', '- Frozen', 'ies'], 
                ['Kippers - Smoked', 'Kippe', 'oked', '- S'], 
                ['Cake - Cheese Cake 9 Inch', 'Cak', 'Cake 9 Inch', 'ese'], 
                ['Food Colouring - Pink', 'Food Colo', ' - Pink', 'ouring - Pi'], 
                ['Soup - Campbells Chili Veg', 'Soup - Camp', ' Chili Veg', 'mpbells '], 
                ['Sugar - Brown', 'Sugar', ' Brown', '- Brown'], 
                ['Trout - Rainbow, Frozen', 'Trout', 'rozen', 'ro'], 
                ['Pork - Kidney', 'Por', 'dney', 'ork'], 
                ['Tea - Herbal Sweet Dreams', 'Tea - ', 'eet Dreams', 'Herbal Sw'], 
                ['Sugar Thermometer', 'Sugar The', 'eter', 'r T'], 
                ['Juice - Lime', 'Juice', 'Lime', 'Ju'], 
                ['Cheese - Marble', 'C', 'rble', 'heese'], 
                ['Instant Coffee', 'Instan', ' Coffee', 't Co'], 
                ['Muffin - Mix - Strawberry Rhubarb', 'Muffin - Mix - S', 'hubarb', 'Mix - Strawberry '], 
                ['Squid - Breaded', 'Sq', 'eaded', 'Breaded'], 
                ['Wine - Maipo Valle Cabernet', 'Wine - M', 'bernet', '- Maipo '], 
                ['Lamb - Pieces, Diced', 'L', 'ces, Diced', 'mb - Piece'], 
                ['Chocolate - Chips Compound', 'Chocolate - ', 'hips Compound', 'Ch'], 
                ['Carroway Seed', 'Carrow', 'y Seed', 'roway S'], 
                ['Chef Hat 25cm', 'Ch', ' 25cm', ' '], 
                ['Pan Grease', 'Pan ', 'ease', 'n'], 
                ['Carrots - Purple, Organic', 'Carrots - Pur', 'Organic', 'rrots - P'], 
                ['Nantucket - Orange Mango Cktl', 'Nantucket', 'e Mango Cktl', ' - O'], 
                ['Juice - Propel Sport', 'Juice -', 'port', 'Prop'], 
                ['Extract - Almond', 'Extract', 'mond', 'act - '], 
                ['Brocolinni - Gaylan, Chinese', 'Brocolinn', 'aylan, Chinese', 'Gaylan, Chin'], 
                ['Langers - Mango Nectar', 'Lange', 'ngo Nectar', 'angers -'], 
                ['Mince Meat - Filling', 'Mince Me', 'ling', 'eat - F'], 
                ['Tea - Herbal - 6 Asst', 'Tea -', ' Asst', 'ea - He'], 
                ['Turkey Leg With Drum And Thigh', 'Turkey Leg Wit', 'm And Thigh', 'h Drum'], 
                ['Appetizer - Escargot Puff', 'Appetize', ' Puff', 'zer -'], 
                ['Celery', 'Cel', 'ery', 'el'], 
                ['Bread Base - Goodhearth', 'Brea', 'earth', 'e - Goodhear'], 
                ['Pork - Hock And Feet Attached', 'Pork - Ho', 'ached', ' - Hock And '], 
                ['Bacardi Mojito', 'Bacard', ' Mojito', 'r'], 
                ['Mints - Striped Red', 'Mints -', 'ed Red', '- '], 
                ['Onions - Cooking', 'Onions ', ' Cooking', ' - '], 
                ['Rum - White, Gg White', 'Rum - ', 'Gg White', ' '], 
                ['Salmon - Whole, 4 - 6 Pounds', 'Salmon -', ', 4 - 6 Pounds', 'Salm'], 
                ['Mushroom - White Button', 'Mushroom', 'hite Button', 'm - W'], 
                ['Tumeric', 'T', 'eric', 'Tume'], 
                ['Amarula Cream', 'Amarula', ' Cream', 'a Crea'], 
                ['Puree - Kiwi', 'Puree', ' Kiwi', 'ree'], 
                ['Bread Fig And Almond', 'Bre', 'nd Almond', 'read'], 
                ['Wine - Ice Wine', 'Wine ', 'e Wine', 'Wine -'], 
                ['Beef - Bones, Marrow', 'B', ', Marrow', ' - Bones'], 
                ['Fondant - Icing', 'Fonda', 'Icing', 't -'], 
                ['Salmon - Whole, 4 - 6 Pounds', 'Sal', ' - 6 Pounds', ' - Whole, 4 -'], 
                ['Wine - Beringer Founders Estate', 'Wine - Beri', 'state', 'i'], 
                ['Yogurt - Blueberry, 175 Gr', 'Yogurt - Bl', ', 175 Gr', 'berry, 175 G'], 
                ['Blackberries', 'Bl', 'ries', 'k'], 
                ['Lettuce - Green Leaf', 'Lettuce -', 'n Leaf', 'ce - Gree'], 
                ['Wine - Marlbourough Sauv Blanc', 'Wine - Ma', 'h Sauv Blanc', 'e'], 
                ['Sambuca - Opal Nera', 'Sa', 'al Nera', 'a - Opal '], 
                ['Sugar Thermometer', 'Sug', 'meter', 'Su'], 
                ['Pepper - Green, Chili', 'Pepper -', 'een, Chili', 'Pepper - Gr'], 
                ['Energy Drink Bawls', 'Energy', ' Bawls', 'ink '], 
                ['Juice - Apple, 500 Ml', 'Juice - A', '00 Ml', 'pl'], 
                ['Milk - Skim', 'Mi', ' Skim', 'k -'], 
                ['Pie Shells 10', 'Pi', 'lls 10', 'Pie She'], 
                ['Pork - Ham Hocks - Smoked', 'Pork - H', 'oked', 'am H'], 
                ['Veal - Striploin', 'V', 'iploin', 'al -'], 
                ['Petite Baguette', 'Petite', 'uette', 'te B'], 
                ['Sun - Dried Tomatoes', 'Sun - D', 'toes', ' Dried '], 
                ['Bread Crumbs - Panko', 'Bread C', '- Panko', 'umbs '], 
                ['Ecolab - Hand Soap Form Antibac', 'Ecolab ', 'ibac', 'and Soap '], 
                ['Beer - True North Strong Ale', 'Beer - T', 'g Ale', '- True N'], 
                ['Pear - Halves', 'Pea', 'lves', '- Halv'], 
                ['Madeira', 'Mad', 'eira', 'adei'], 
                ['Island Oasis - Ice Cream Mix', 'Island Oa', ' Cream Mix', ' '], 
                ['Nantucket - Kiwi Berry Cktl.', 'Nan', 'wi Berry Cktl.', 'ntucket - '], 
                ['Chicken - Leg, Boneless', 'Chicken - Le', 'neless', 'cke'], 
                ['Pail With Metal Handle 16l White', 'Pail W', 'White', 'h Metal Hand'], 
                ['Thyme - Dried', 'Th', ' Dried', '- D'], 
                ['Sandwich Wrap', 'Sandwi', ' Wrap', 'dw'], 
                ['Cheese - Cottage Cheese', 'C', 'e Cheese', 'se - Cotta'], 
                ['Gherkin', 'G', 'rkin', 'rkin'], 
                ['Rum - Dark, Bacardi, Black', 'Rum - ', 'cardi, Black', ' - Dark, B'], 
                ['Quail - Whole, Boneless', 'Quail - ', 'eless', 'ole, Bon'], 
                ['Pepper - Green', 'Peppe', '- Green', 'Peppe'], 
                ['Rabbit - Legs', 'R', ' Legs', 'Ra'], 
                ['Extract - Almond', 'Extr', 'mond', 't - Al'], 
                ['Spring Roll Veg Mini', 'S', ' Veg Mini', 'Spring R'], 
                ['Bag - Bread, White, Plain', 'Bag - Bread', 'lain', ' Br'], 
                ['Sherry - Dry', 'Sherry', '- Dry', 'her'], 
                ['Taro Leaves', 'T', 'aves', 'aro L'], 
                ['Bread - Ciabatta Buns', 'Bread - C', 'atta Buns', ' Ciabatta'], 
                ['Chicken - Ground', 'C', 'ound', ' - Grou'], 
                ['Cheese - Wine', 'Cheese', '- Wine', '- Win'], 
                ['Yogurt - Cherry, 175 Gr', 'Yogurt - ', '175 Gr', ' - C'], 
                ['Wine - Magnotta - Cab Franc', 'Win', ' Cab Franc', 'tta - Ca'], 
                ['Cheese - Ermite Bleu', 'C', ' Bleu', 'Ermite'], 
                ['Beer - Sleeman Fine Porter', 'Beer - Sle', 'Porter', 'er '], 
                ['Bread - Flat Bread', 'Br', 'at Bread', 'lat '], 
                ['Duck - Legs', 'Duck ', 'Legs', 'k - L'], 
                ['Container - Clear 16 Oz', 'Conta', ' 16 Oz', 'ner - Clear'], 
                ['Sauce - Balsamic Viniagrette', 'Sauce - ', 'agrette', 'uce - B'], 
                ['Beef - Tongue, Fresh', 'Be', ', Fresh', 'gue, Fres'], 
                ['Sugar - Monocystal / Rock', 'Su', 'l / Rock', 'onocys'], 
                ['Wine - Mondavi Coastal Private', 'Wine - Mon', 'Private', 'ine - Mondavi C'], 
                ['Butter - Salted, Micro', 'Butter - S', 'icro', 'alted, M'], 
                ['Pepper - Cubanelle', 'Pepper -', 'Cubanelle', '- '], 
                ['Sprouts - Alfalfa', 'Sprouts ', 'alfa', 'r'], 
                ['Soup - Campbells, Spinach Crm', 'Soup -', ' Crm', 'oup - '], 
                ['Longos - Greek Salad', 'Longos', 'ek Salad', '- '], 
                ['Salmon - Atlantic, No Skin', 'Salmon -', ' Skin', ' Atlantic,'], 
                ['Mint - Fresh', 'Mint -', 'Fresh', 'int'], 
                ['Arizona - Green Tea', 'Arizo', 'reen Tea', 'izona - Gr'], 
                ['Cup - 4oz Translucent', 'C', 'lucent', ' 4oz '], 
                ['Wine - White, Lindemans Bin 95', 'W', 'Bin 95', 'e - '], 
                ['Sobe - Cranberry Grapefruit', 'Sobe - Cranbe', 'ry Grapefruit', 'berr'], 
                ['Chick Peas - Dried', 'Chi', ' Dried', ' Peas'], 
                ['Scallops - Live In Shell', 'Scallops -', ' In Shell', '- Live In Sh'], 
                ['Sping Loaded Cup Dispenser', 'Sping ', 'spenser', 'Sping Loade'], 
                ['Veal - Insides, Grains', 'Veal -', 's, Grains', ' Insides,'], 
                ['Rice - Sushi', 'Ri', 'ushi', 'ce - S'], 
                ['Jolt Cola - Red Eye', 'Jolt', ' Eye', '- Red'], 
                ['Noodles - Cellophane, Thin', 'Noodle', 'lophane, Thin', 'odles - Cell'], 
                ['Muffin Mix - Oatmeal', 'Muffin', ' Oatmeal', 'uffin Mix'], 
                ['Pastry - Carrot Muffin - Mini', 'Pastry - Car', 'ffin - Mini', 'ot Muffin '], 
                ['Longos - Grilled Salmon With Bbq', 'Longos - Gril', 'h Bbq', 'illed '], 
                ['Mountain Dew', 'M', 'n Dew', 'i'], 
                ['Swiss Chard - Red', 'Swiss ', ' - Red', 'ss'], 
                ['Nut - Pecan, Halves', 'Nut -', 'alves', '- Pecan, '], 
                ['Transfer Sheets', 'Tran', 'heets', 'ans'], 
                ['Goldschalger', 'G', 'alger', 'schalg'], 
                ['Olives - Black, Pitted', 'Olive', 'ack, Pitted', 'ack, P'], 
                ['Coffee - Flavoured', 'Coffee -', 'oured', 'ee '], 
                ['Lettuce - Escarole', 'Let', 'arole', 'e - Esc'], 
                ['Turkey - Breast, Smoked', 'Turke', ', Smoked', 'key - Breas'], 
                ['Ginger - Ground', 'Ginger -', 'ound', 'r - '], 
                ['7up Diet, 355 Ml', '7u', ' 355 Ml', ', 355'], 
                ['Cheese - Goat With Herbs', 'C', 't With Herbs', '- Goat'], 
                ['Pears - Fiorelle', 'P', 'Fiorelle', '- Fiorel'], 
                ['Nantucket - 518ml', 'Nantuc', ' - 518ml', 'tuck'], 
                ['Pasta - Detalini, White, Fresh', 'Pasta - Det', ', Fresh', '- D'], 
                ['General Purpose Trigger', 'General Pu', 'igger', 'enera'], 
                ['Dr. Pepper - 355ml', 'Dr. Pepp', '- 355ml', 'Peppe'], 
                ['Caviar - Salmon', 'C', ' Salmon', 'iar - Sa'], 
                ['Chilli Paste, Sambal Oelek', 'Chi', ' Sambal Oelek', ' Paste, S'], 
                ['Sauce - Mint', 'S', '- Mint', 'e'], 
                ['Wine - Magnotta - Cab Sauv', 'Wine - Ma', 'b Sauv', 'Wine -'], 
                ['Beef - Tongue, Fresh', 'Beef -', ', Fresh', 'f - To'], 
                ['Appetizer - Mini Egg Roll, Shrimp', 'Appe', 'll, Shrimp', 'Egg Roll, Shr'], 
                ['Puree - Mango', 'Pu', 'ango', ' M'], 
                ['Oil - Olive Bertolli', 'Oil - ', 'Bertolli', 'il - O'], 
                ['Wine - Pinot Noir Stoneleigh', 'Wine -', 'neleigh', ' '], 
                ['Container Clear 8 Oz', 'Co', 'ar 8 Oz', 'nt'], 
                ['Spinach - Spinach Leaf', 'Spin', 'ch Leaf', 'nac'], 
                ['Spice - Montreal Steak Spice', 'Spice - Mont', 'pice', 'Spice - Mont'], 
                ['Veal - Striploin', 'Veal ', 'iploin', 'tripl'], 
                ['Mayonnaise - Individual Pkg', 'Mayonnaise - I', 'idual Pkg', 'e - In'], 
                ['Cheese - Asiago', 'Cheese', 'Asiago', 'heese'], 
                ['Salmon - Atlantic, Skin On', 'Salmon - Atla', 'c, Skin On', 'lan'], 
                ['Paper Cocktail Umberlla 80 - 180', 'Pap', 'erlla 80 - 180', 'tail Umberlla 80'], 
                ['Tequila Rose Cream Liquor', 'Tequi', 'Liquor', 'u'], 
                ['Muffin - Mix - Strawberry Rhubarb', 'Muffi', 'berry Rhubarb', 'in - M'], 
                ['Bread - Focaccia Quarter', 'Brea', 'a Quarter', 'd - F'], 
                ['Bread - Hamburger Buns', 'Brea', 'ger Buns', 'Hamburger'], 
                ['Wine - Sauvignon Blanc Oyster', 'Wine - S', 'lanc Oyster', 'uvignon '], 
                ['Wine - Toasted Head', 'W', 'ted Head', 'in'], 
                ['Cheese - Romano, Grated', 'Cheese', 'Grated', 'e - Rom'], 
                ['Tea - Lemon Green Tea', 'Tea - ', ' Green Tea', 'ea - Lemo'], 
                ['Sauce - Demi Glace', 'Sa', 'mi Glace', '- D'], 
                ['Syrup - Monin - Blue Curacao', 'Syrup - M', 'ue Curacao', ' Mo'], 
                ['Banana - Leaves', 'Banan', 'eaves', '- L'], 
                ['Squid - Breaded', 'Sq', 'eaded', 'Squi'], 
                ['Bread - Pita, Mini', 'Br', 'ita, Mini', '- Pita, '], 
                ['Wine - Clavet Saint Emilion', 'Wi', ' Emilion', ' Clavet S'], 
                ['Nantucket Cranberry Juice', 'Nantucket C', 'ry Juice', 'uc'], 
                ['Cheese - Bakers Cream Cheese', 'Cheese ', 'eam Cheese', '- '], 
                ['Wine - Kwv Chenin Blanc South', 'Wine - Kw', 'c South', 'ne - Kwv C'], 
                ['Compound - Strawberry', 'Compoun', 'trawberry', 'Straw'], 
                ['Fish - Base, Bouillion', 'Fish - Base', 'uillion', 'se, Bouilli'], 
                ['Ecolab - Solid Fusion', 'Ecolab ', 'lid Fusion', ' Solid Fus'], 
                ['Stock - Veal, Brown', 'St', ' Brown', 'ock '], 
                ['Water - Spring Water, 355 Ml', 'Wate', 'Water, 355 Ml', 'ter - Spring W'], 
                ['Mushroom - Oyster, Fresh', 'Mushroom - O', ' Fresh', '- '], 
                ['Cookies - Englishbay Oatmeal', 'Cookies - ', 'meal', 'lishb'], 
                ['Beef - Top Butt', 'Beef - ', 'op Butt', 'ef - T'], 
                ['Beef - Ground Medium', 'Bee', ' Medium', 'f'], 
                ['Soup - Base Broth Beef', 'Sou', 'th Beef', 'p - Base'], 
                ['Soup - Campbells - Tomato', 'Soup - Campbe', 'omato', '- Cam'], 
                ['Roe - Lump Fish, Black', 'Ro', 'lack', ' - L'], 
                ['Chinese Foods - Chicken Wing', 'Chinese Foods', '- Chicken Wing', 'oods - Chick'], 
                ['Onions - White', 'Oni', 'White', 'nio'], 
                ['Scallops - Live In Shell', 'Scallop', 'ive In Shell', 'llops - Li'], 
                ['Coffee - Cafe Moreno', 'C', 'reno', 'offee - '], 
                ['Wine - Magnotta - Pinot Gris Sr', 'Win', 't Gris Sr', ' - Pinot Gr'], 
                ['Banana - Leaves', 'B', ' Leaves', 'a - Leav'], 
                ['Muffin Batt - Blueberry Passion', 'Muffin Batt -', ' Passion', 'fin Batt'], 
                ['Duck - Whole', 'Duck ', 'Whole', 'ck'], 
                ['Alize Red Passion', 'Ali', 'sion', 'd Pas'], 
                ['Emulsifier', 'Emul', 'ifier', 'ifier'], 
                ['Apple - Macintosh', 'Apple - ', 'ntosh', 'ple -'], 
                ['Banana', 'Ba', 'nana', 'ana'], 
                ['Stock - Veal, Brown', 'Stock - V', 'al, Brown', ' - Vea'], 
                ['Quail - Jumbo', 'Qu', ' Jumbo', 'l - J'], 
                ['Bread - Triangle White', 'Bread - ', 'e White', '- Trian'], 
                ['Napkin Colour', 'Nap', 'Colour', 'apkin C'], 
                ['Beans - Fava Fresh', 'Beans', 'resh', '- Fava'], 
                ['Chinese Lemon Pork', 'Chinese ', 'n Pork', 'emon Po'], 
                ['Quail - Whole, Boneless', 'Quail ', 'Boneless', ' Whole, Bone'], 
                ['Coffee Beans - Chocolate', 'Coffee Beans', 'Chocolate', 'ff'], 
                ['Veal - Slab Bacon', 'Veal ', 'Bacon', 'Ve'], 
                ['Mushroom - King Eryingii', 'Mushroom', 'Eryingii', 'room - Kin'], 
                ['Table Cloth 54x54 White', 'Tab', 'hite', 'loth 54x54 W'], 
                ['Toamtoes 6x7 Select', 'Toa', '7 Select', ' 6x'], 
                ['Steam Pan Full Lid', 'Steam Pan', ' Full Lid', ' Full L'], 
                ['Beans - Black Bean, Canned', 'Beans - ', 'nned', 'Black Bean, C'], 
                ['Soup - Campbells Beef Stew', 'Soup ', ' Stew', 'Campbe'], 
                ['Glass - Wine, Plastic, Clear 5 Oz', 'Glass', 'r 5 Oz', 'ne, Plastic'], 
                ['Compound - Orange', 'Compoun', 'ange', 'o'], 
                ['Pears - Fiorelle', 'Pears', 'iorelle', 'ars - Fi'], 
                ['Horseradish Root', 'Hor', ' Root', 'dish '], 
                ['Artichoke - Bottom, Canned', 'Artic', 'ttom, Canned', ' -'], 
                ['Nescafe - Frothy French Vanilla', 'Nescafe -', ' French Vanilla', 'cafe '], 
                ['Muffin Orange Individual', 'Muffi', 'ividual', 'n Ora'], 
                ['Lentils - Green Le Puy', 'Lentils -', 'e Puy', ' '], 
                ['Veal - Kidney', 'Veal', 'idney', ' Ki'], 
                ['Kale - Red', 'Kale', '- Red', 'Ka'], 
                ['Horseradish Root', 'Horsera', 'h Root', 'Horsera'], 
                ['Puree - Blackcurrant', 'Puree -', 'ackcurrant', ' - Bl'], 
                ['Beef - Montreal Smoked Brisket', 'Beef - Mo', 'oked Brisket', 'ontr'], 
                ['Zucchini - Mini, Green', 'Zucchini - ', 'reen', 'cchini'], 
                ['Goat - Whole Cut', 'Goat ', 'le Cut', ' Whole'], 
                ['Rice - Wild', 'Ri', ' Wild', ' '], 
                ['Juice - Orange 1.89l', 'Juice - O', '1.89l', 'i'], 
                ['Cheese - Cambozola', 'Chees', 'ambozola', 'se '], 
                ['Butter - Salted', 'Butter -', 'lted', 'r '], 
                ['Lentils - Green Le Puy', 'Lentils -', ' Puy', 'ntils '], 
                ['Beef - Cow Feet Split', 'Be', 'plit', ' Feet S'], 
                ['Truffle Cups - Brown', 'Truffle', '- Brown', ' C'], 
                ['Cognac - Courvaisier', 'Cognac - ', 'ourvaisier', 'gna'], 
                ['Chocolate - Milk, Callets', 'C', ' Callets', 'ocolate - Mil'], 
                ['Soup - Knorr, Chicken Noodle', 'Soup - Knorr', 'n Noodle', 'up - Knorr, '], 
                ['Towels - Paper / Kraft', 'Towels ', 'per / Kraft', 's - P'], 
                ['Crab - Meat Combo', 'Crab - ', 'at Combo', ' - Meat C'], 
                ['Milk 2% 500 Ml', 'M', '0 Ml', ' 2% '], 
                ['Goldschalger', 'Golds', 'alger', 'olds'], 
                ['Wine - Fino Tio Pepe Gonzalez', 'Wine - Fino T', 'epe Gonzalez', 'Fino T'], 
                ['Syrup - Pancake', 'Sy', 'ancake', ' - Pa'], 
                ['Chinese Foods - Thick Noodles', 'C', 'odles', 'o'], 
                ['Vinegar - Cider', 'Vin', 'ider', 'ine'], 
                ['Pork - Sausage, Medium', 'Pork - Sa', 'Medium', 'k - S'], 
                ['Peppercorns - Green', 'Peppercor', 'Green', 'ppe'], 
                ['Wine - Masi Valpolocell', 'Wine', 'lpolocell', ' Valpolo'], 
                ['Liners - Baking Cups', 'Liner', 'ng Cups', 'iners '], 
                ['Apples - Spartan', 'Apples -', 'rtan', ' Spartan'], 
                ['Flour - Corn, Fine', 'Flour - C', 'Fine', 'r - Cor'], 
                ['Kiwano', 'Ki', 'wano', 'wan'], 
                ['Corn Meal', 'Cor', 'Meal', 'n M'], 
                ['Canadian Emmenthal', 'Canad', 'nthal', 'adi'], 
                ['Versatainer Nc - 888', 'V', 'c - 888', 'tainer Nc'], 
                ['Truffle Cups - Red', 'T', ' - Red', ' Cups'], 
                ['Crab - Imitation Flakes', 'C', 'tion Flakes', 'itat'], 
                ['Fennel', 'Fe', 'nnel', 'F'], 
                ['Wine - White, Chardonnay', 'Wine', 'onnay', 'ine - Whit'], 
                ['Soup - Campbells Asian Noodle', 'Soup - Campb', 'an Noodle', 'bells Asian N'], 
                ['Wine - Cahors Ac 2000, Clos', 'Wine ', ' Clos', 'rs Ac 20'], 
                ['Flower - Leather Leaf Fern', 'Flo', 'f Fern', 'ather '], 
                ['Devonshire Cream', 'Devonsh', ' Cream', 'nshire C'], 
                ['Aspic - Clear', 'Aspic', ' Clear', 'pi'], 
                ['Chicken - Base', 'Chi', ' - Base', 'C'], 
                ['Vinegar - Balsamic', 'Vinega', ' Balsamic', ' - Ba'], 
                ['Transfer Sheets', 'Tr', 'eets', 'Trans'], 
                ['Coffee - Ristretto Coffee Capsule', 'Coffee - Ristre', 'o Coffee Capsule', 'e'], 
                ['Capicola - Hot', 'Capic', 'a - Hot', 'apicola'], 
                ['Wine - Red Oakridge Merlot', 'Wine - Re', 'e Merlot', 'ne - Red O'], 
                ['Cheese - St. Paulin', 'Cheese - S', 'aulin', 'eese - St'], 
                ['Milk - Buttermilk', 'Milk -', 'rmilk', 'u'], 
                ['Garlic - Elephant', 'Garlic -', 'phant', 'arlic - '], 
                ['Energy Drink - Franks Pineapple', 'Energy ', ' Pineapple', '- '], 
                ['Bandage - Fexible 1x3', 'Ba', ' 1x3', 'da'], 
                ['Pepper - Chili Powder', 'Pe', 'i Powder', 'r - Chil'], 
                ['Bread Base - Goodhearth', 'Bread Ba', ' Goodhearth', 'read Base'], 
                ['Ice Cream Bar - Drumstick', 'Ice Cr', ' - Drumstick', 'Cream B'], 
                ['Buttons', 'But', 'ons', 'tons'], 
                ['Butter Sweet', 'But', ' Sweet', 'utter '], 
                ['Wine - Spumante Bambino White', 'Wine - Spumante', 'White', 'umante'], 
                ['Cheese - Bocconcini', 'Cheese - ', 'cini', 'Bocconc'], 
                ['Parsley Italian - Fresh', 'Parsley I', '- Fresh', 'arsley Itali'], 
                ['Cake Sheet Combo Party Pack', 'Cake Shee', 'bo Party Pack', 'ke Sh'], 
                ['Praline Paste', 'Praline', 'aste', 'ne P'], 
                ['Pepper - Green, Chili', 'Pep', 'hili', ' - Green, C'], 
                ['Bag - Regular Kraft 20 Lb', 'Bag - Reg', ' Kraft 20 Lb', 'Regular Kr'], 
                ['Chicken - Tenderloin', 'Chicken -', 'rloin', 'cken - '], 
                ['Cocoa Powder - Natural', 'Cocoa Po', ' - Natural', 'a P'], 
                ['Bar Mix - Pina Colada, 355 Ml', 'Bar Mix - P', 'Colada, 355 Ml', ' Pina '], 
                ['Appetizer - Cheese Bites', 'A', 'heese Bites', 'ppetizer -'], 
                ['Longos - Chicken Curried', 'Lo', 'rried', ' Chicken C'], 
                ['Cookie Dough - Peanut Butter', 'Cookie Doug', 'eanut Butter', 'ugh - Peanut'], 
                ['Cheese - Cottage Cheese', 'Chee', 'Cheese', ' - Cott'], 
                ['Oil - Sesame', 'Oi', 'same', ' - '], 
                ['Extract - Rum', 'E', ' Rum', 't -'], 
                ['Pepper - Cayenne', 'Pepper -', 'enne', 'r - C'], 
                ['Wine - Ruffino Chianti', 'Wi', 'o Chianti', '- Ruffi'], 
                ['Ecolab Silver Fusion', 'Ecolab Si', 'er Fusion', 'olab '], 
                ['Pork - Loin, Center Cut', 'Pork - L', 'er Cut', 'k - '], 
                ['Pails With Lids', 'Pails Wi', ' Lids', 'ith L'], 
                ['Green Scrubbie Pad H.duty', 'Gre', 'duty', 'crubbie '], 
                ['Smoked Paprika', 'Smok', 'aprika', 'd Papr'], 
                ['Wine - Semi Dry Riesling Vineland', 'Wi', 'neland', 'Semi Dr'], 
                ['Pastry - Key Limepoppy Seed Tea', 'Pastry - ', 'epoppy Seed Tea', 'Li']
        ];
    }    

}